gonum/plot

- plot/axis.go
- plot/draw.go
- plot/legend.go
- plot/plot.go
- plotter/barchart.go
- plotter/boxplot.go
- plotter/bubbles.go
- plotter/bubbles_test.go
- plotter/errbars.go
- plotter/functions.go
- plotter/glyphbox.go
- plotter/grid.go
- plotter/histogram.go
- plotter/labels.go
- plotter/line.go
- plotter/main.go
- plotter/plotter.go
- plotter/quartile.go
- plotter/scatter.go
- plotutil/add.go
- plotutil/errorpoints.go
- plotutil/errorpoints_test.go
- plotutil/main.go
- plotutil/plotutil.go
- vg/font.go
- vg/vgeps/vgeps.go
- vg/vgimg/vgimg.go
- vg/vgpdf/vgpdf.go
- vg/vgsvg/vgsvg.go
Also run goimports on all files.
> all: update import paths

- .test-coverage.sh
- .travis.yml
- README.md
* add travis-ci integration
* add coveralls.io integration
* add CI flair to README.md
> Add travis ci

- AUTHORS
- axis.go
- gob/gob.go
- legend.go
- plot.go
- plot_test.go
- plotter/barchart.go
- plotter/boxplot.go
- plotter/bubbles.go
- plotter/errbars.go
- plotter/functions.go
- plotter/glyphbox.go
- plotter/grid.go
- plotter/histogram.go
- plotter/labels.go
- plotter/line.go
- plotter/main.go
- plotter/plotter.go
- plotter/quartile.go
- plotter/scatter.go
- plotutil/add.go
- plotutil/errorpoints_test.go
- plotutil/main.go
- plotutil/plotutil.go
- vg/draw/canvas.go
- vg/len.go
- vg/vgeps/vgeps.go
- vg/vgimg/vgimg.go
- vg/vgsvg/vgsvg.go
- add vgdraw.Canvas (in replacement of plot.DrawArea)
- introduce vg.Inch, vg.Centimeter and vg.Millimeter
- introduce plot.Ticker interface
- introduce plot.Normalizer interface
- support for persistency
> Gonum redesign vgdraw

- palette/palette.go
- palette/palette_test.go
Formalise the notion already existing in the brewer package.
> palette: add DivergingPalette interface

- axis.go
- legend.go
- plot.go
- plotter/barchart.go
- plotter/boxplot.go
- plotter/bubbles.go
- plotter/contour.go
- plotter/errbars.go
- plotter/functions.go
- plotter/glyphbox.go
- plotter/grid.go
- plotter/heat.go
- plotter/histogram.go
- plotter/labels.go
- plotter/line.go
- plotter/quartile.go
- plotter/scatter.go
- vg/draw/canvas.go
- make `vg/draw.Rect` a `Rectangle{Min,Max Point}`
- fixes #13
> Issue 13 rect

- gob/gob_test.go
It was getting in the way of other tests in plot and it is really a gob test, not a plot test.
Also added header and made organisation clearer.
@sbinet @eaburns @gonum/developers
> Clean up gob tests and move into plot/gob

- plot.go
> plot: make Save take locale agnostic units

- README.md
- add godoc badge
- add documentation+installation sections
- add godoc link
- remove stray spaces
- mention X-Window backend
> doc: add links to godoc

- axis.go
- axis_test.go
> plot: fix near-zero rounding errors

- vg/vg_test.go
> vg: use plot WriterTo in tests

- axis.go
> Fix tics when the maximum tic is negative.

- vg/vg_test.go
golang/go@53efe1e121e68fe changed and improved `compress/flate`'s
matching algorithm.
This breaks tests that rely on stable on-disk byte content.
Instead, decode the image.Image from the raw []byte content and compare
the resulting decoding images.
For PDF images, decode the raw []byte using rsc.io/pdf.Reader and
compare each page's content.
> vg: make TestLineWidth more reliable

- vg/vg.go
> vg: fix Canvas.SetColor godoc string

- axis.go
- legend.go
- plot.go
- plot_test.go
- plotter/barchart.go
- plotter/boxplot.go
- plotter/bubbles.go
- plotter/contour.go
- plotter/errbars.go
- plotter/functions.go
- plotter/glyphbox.go
- plotter/heat.go
- plotter/histogram.go
- plotter/labels.go
- plotter/line.go
- plotter/quartile.go
- plotter/scatter.go
- vg/draw/canvas.go
- vg/draw/draw_test.go
- vg/geom.go
> vg: migrate draw.Point+draw.Rectangle back to vg

- axis.go
- legend.go
- plot.go
- plotter/labels.go
- vg/draw/canvas.go
Fixes #274.
@sbinet @eaburns Please take a look.
> vg/draw: update Canvas.FillText signature for consistency

- axis.go
- axis_test.go
Fixes #301.
@jasonpfox @sbinet @eaburns Please take a look.
> plot: make tick labels non-ambiguous

- axis_test.go
> plot: improve test reporting

- plotter/heat.go
- plotter/heat_test.go
> plotter: explicitly panic when HeatMap.Min >= HeatMap.Max

- internal/bezier/bezier.go
- internal/bezier/bezier_test.go
- plotter/sankey.go
@btracey Please take a look.
As the sole author of bezier I am altering the license to the gonum license.
It is internal at this stage but could be made public - in thaat event I will delete the bíogo package and point here for my uses.
Fixes #340.
> plotter: remove dependency on bíogo

- vg/vgimg/vgimg.go
> vg/vgimg: add Image to vgimg.Canvas

- legend.go
A very minor change, but hopefully a positive one that you will consider. Regards, Sam.
> Typo and grammatical correction in legend.go

- .gitignore
- internal/cmpimg/cmpimg.go
- vg/vgtex/canvas_test.go
> vg/vgtex: fix example

- internal/cmpimg/cmpimg.go
> Cmpimg go 1.6

- plotter/contour.go
> plotter: check for negative Z-range

- plotter/contour.go
- plotter/heat.go
> plotter: improve panic strings for HeatMap and Contour

- plot.go
> plot: simplify cropping call

- vg/vgimg/vgimg.go
- vg/vgimg/vgimg_test.go
> fix datarace in defaultFontCache

- .github/ISSUE_TEMPLATE
> github: ask for gonum/plot rather than gonum proper

- vg/vgeps/vgeps.go
- vg/vgsvg/vgsvg.go
- vg/vgtex/canvas.go
Harmonize the `context` API across `vgeps`, `vgsvg` and `vgtex` backends.
> Harmonize vg stack

- go.mod
> Vgo support

- palette/moreland/convert_test.go
- palette/moreland/luminance_test.go
> moreland: Add tolerance for tests

- go.mod
> all: update Go module with x/exp dependency

- plotter/polygon.go
- plotter/polygon_test.go
> plotter: Fix line clipping bug

- .travis.yml
> travis: add Go1.11.x, drop Go1.8.x

- plotter/sankey_test.go
> plotter: gofmt -s

- axis.go
- axis_test.go
Allows to create a Ticker using a function with a matching signature.
> plot: allow to use functions as Tick.Markers

- README.md
- appveyor.yml
> all: add Windows CI

- axis.go
- labelling.go
- labelling_test.go
- plot_test.go
> plot: make sure there is enough ULP space for axis ranges

- go.mod
- go.sum
- vg/vgimg/vgimg.go
> vg/vgimg: handle dash offsets

- .travis.yml
- appveyor.yml
> ci: update supported versions

- appveyor.yml
> ci: comment out go1.12 until appveyor update

- plotter/conrec.go
- tools/bezier/bezier.go
This commit rewrites some if-else-if-else chains as a switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
> rewrite if-else to switch statement

- align_test.go
- legend_test.go
- palette/moreland/example_test.go
- plotter/barchart_test.go
- plotter/boxplot_test.go
- plotter/bubbles_test.go
- plotter/colorbar_test.go
- plotter/errbars_test.go
- plotter/functions_test.go
- plotter/general_test.go
- plotter/heat_test.go
- plotter/histogram_test.go
- plotter/image_test.go
- plotter/polygon_test.go
- plotter/quartile_test.go
- plotter/rotation_test.go
- plotter/sankey_test.go
- plotter/scatterColor_test.go
- plotter/scatter_test.go
- plotter/timeseries_test.go
- plotutil/errorpoints_test.go
- vg/vgtex/canvas_test.go
> all: put all examples in a xyz_test package

- vg/vg.go
> vg: document behaviour of zero font size text

- plotter/heat.go
- plotter/heat_test.go
> plotter: fix documentation typo and clarify example

- plotter/field.go
- plotter/field_test.go
- plotter/heat.go
- plotter/heat_test.go
> plotter: handle cases in HeatMap and Field with single width/height

- .github/ISSUE_TEMPLATE
> github: add note about using play.golang.org

- .travis.yml
- appveyor.yml
- go.mod
> ci: drop Go-1.10, add Go-1.13

- vg/example_test.go
> vg: add example for user defined font

- go.mod
- go.sum
> modules: use fogleman/gg@v1.3.0

- LICENSE
> LICENSE: copy license text from gonum.org/v1/gonum

- axis.go
- plot.go
> plot: introduce unexported orientation type

- vg/vgimg/example_vgimg_test.go
> vg/vgimg: add examples for the UseXYZ options

- vg/vgtex/canvas.go
- vg/vgtex/example_canvas_test.go
- vg/vgtex/testdata/scatter_golden.tex
> vg/vgtex: correctly handle opacity

- vg/vgtex/canvas.go
- vg/vgtex/example_canvas_test.go
- vg/vgtex/testdata/scatter_golden.tex
> vg/vgtex: properly handle font size changes

- vg/vgtex/canvas.go
- vg/vgtex/testdata/linestyle_golden.tex
- vg/vgtex/testdata/scatter_golden.tex
> vg/vgtex: handle solid lines through empty pgfsetdash

- vg/tee.go
- vg/tee_test.go
- vg/vg.go
> vg: introduce MultiCanvas, a tee for canvases

- .github/FUNDING.yml
> github: add FUNDING.yml

- .travis.yml
- appveyor.yml
- go.mod
- go.sum
- palette/moreland/convert_test.go
- palette/moreland/luminance_test.go
> all: bump to Go-1.15

- plotter/volcano_example.go
> plotter: fix volcano example

- .codecov.yml
> codecov: make coverage report relative to root of the repo

- README.md
I was excited to hear that this functionality had been merged, and I thought it might warrant a mention in the README.
> doc: mention new vector graphics backend in README

- vg/vgimg/vgimg.go
> vg/vgimg: properly close font.Face after use

- .github/workflows/codecov.yml
> ci: add codecov.yml with master branch report upload

- go.mod
- go.sum
- vg/vggio/context.go
> vg/vggio: update to new gioui/op Save/Load state management API

- .github/workflows/ci.yml
- .travis.yml
- go.mod
- go.sum
Signed-off-by: Sebastien Binet <binet@cern.ch>
> ci: bump to Go-1.16

- go.mod
- go.sum
Updates gonum/plot#669.
Signed-off-by: Sebastien Binet <binet@cern.ch>
> plot: update go-latex dependency

- vg/draw/doc.go
Fixes gonum/plot#678.
Signed-off-by: Sebastien Binet <binet@cern.ch>
> vg/draw: add package level documentation

- vg/vgpdf/vgpdf.go
> vg/vgpdf: remove use of vg.FontMap, retrieve TTF data from sfnt.Font

- plotutil/main.go
> plotutil: fix /main.go with no-err New plot function

- .github/workflows/golangci-lint.yml
- cmpimg/cmpimg.go
> cmpimg: properly handle images of different types

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- go.mod
- palette/brewer/generate_complete_palettes.go
- palette/brewer/generate_palettes.go
- plotutil/main.go
- version.go
- vg/fonts/mk-fonts.go
- vgall.go
> all: add Go-1.17, drop Go-1.15

- font/font_test.go
> all: apply gofmt -s

- .github/FUNDING.yml
> github: remove kortschak from FUNDING.yml

- go.mod
- go.sum
> all: bump gonum@v0.9.3 fpdf@v0.5.0 and svgo@v0.0.0-20210923152817

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/golangci-lint.yml
- appveyor.yml
- go.mod
- go.sum
> all: add Go-1.18, drop Go-1.16

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- go.mod
> all: bump Go-1.24, drop Go-1.22
