gonum/plot

.travis.yml
The wrong environment variable was set, which prevented coveralls.io
from showing a coverage badge.
=> fix COVERALLS_TOKEN secure environment variable

vg/vgimg/vgimg.go, vg/vgx11/canvas.go, vg/vgx11/main.go, vg/vgx11/painter.go
- adds support for `X11` on unix (ie: `!windows`)
needs #9
=> vgx11: an X11-based backend

plotter/johnson.go
This was raised in code review for gonum/graph#34. The code was changed, but the comment was left. Now the comment points to the correct WP revision.
=> Fix algorithm origin comment

vg/draw/canvas.go, vg/draw/draw_test.go
There is an issue with the draw.Canvas.Crop() function. I've added a test to document it. The test does cropping two different ways, the rectangles of which should be the same, and produces two output images that should also be the same. In the current version the two methods yield different results. The change that I made fixes this bug.
=> Fixed cropping bug

vg/font.go
Concurrent add operations would have potentially resulted in memory corruption.
=> Fix use of RW mutex

plotter/main.go
Semantically the same as prior to #183.
@btracey @eaburns
=> Make example code match Save unit semantics

.travis.yml, vg/vgimg/vgimg_test.go, vg/vgx11/canvas.go, vg/vgx11/canvas_test.go
Address issue #179  by translating the image to (0,-h) so (0,0) is at the
bottom-left corner for the X11 backend.
``go test ./...`` will skip the X11 test if ``$DISPLAY`` is not defined.
=> vgx11: fix translate offset

plot.go, vg/draw/canvas.go, vg/vg.go
This is a first stab at implementing a generalised plot writing method as suggested [here](https://github.com/gonum/plot/pull/186#discussion_r27268402).
I'm not completely happy with it for a couple of reasons: 1. we lose the title in eps (I'm less concerned about this) and 2. it's not extensible.
Addressing the second point. If we have a map[string]func(w, h vg.Length) interface { vg.CanvasSizer; io.WriterTo } that can be registered to, then this problem goes away. This map must be in vg, and referenced from the WriterTo method. Then each vg implementation that can make a WriterTo will register in an init.
=> plot: add WriterTo method to Plot

plotter/johnson.go
Previously we did not remove any nodes under s if they were a predecessor.
=> plotter: fix Johnson graph.subgraph method

axis.go, axis_test.go
There are floating point errors in computing the tick value, which are eliminated by rounding to a float32. If the value is close to zero, this doesn't remove the rounding errors. If abs(value) < 1, add 1, convert to float32, and then subtract one. This fixes cases where there are a lot of digits for the axis label at 0
=> Fix label rounding for small tick value.

vg/vgimg/vgimg.go, vg/vgx11/canvas.go
- `code.google.com/p/xyz` will be retired
- migrate to the new home of `draw2d`
=> all: use github.com/llgcode/draw2d

plot.go, plotter/main.go, vg/draw/canvas.go, vg/draw/draw_test.go, vg/vg.go
I've created a method for tiling the canvas to make subfigures, and I have also changed the plotter examples to be put into subfigures instead of a bunch of individual files. PTAL.
=> added method for canvas tiles; changed plotter examples to tiles

vg/vgx11/canvas_test.go
Temporarily disable vgx11 test
Updates #220.
=> vgx11: temporarily disable test

plot_test.go, vg/draw/draw_test.go, vg/len.go, vg/recorder/recorder.go, vg/recorder/recorder_test.go, vg/vg.go, vg/vgeps/vgeps.go, vg/vgimg/vgimg.go, vg/vgpdf/vgpdf.go, vg/vgsvg/vgsvg.go
The DPI value is only ever used internally by types to determine the number of dots for a given Length, the alternative is to give the Dots method the DPI value rather than the Canvas.
The DPI method is retained on types that need to know their resolution, although this could be made unexported.
@eaburns This is exploratory, so I'm not fussed if you reject it, but it does drop one method from the vg.Canvas set and it doesn't really look like it impacts in a negative way to my mind. Please take a look.
=> vg: drop DPI from Canvas

vg/len.go, vg/vg_test.go
Making vg.Length implement flag.Value allows for nicer CLI, such
as:
$ my-cmd -plot-x-size=20cm -plot-y-size=15cm
=> vg: provide ParseLength to create a vg.Length from a string

.travis.yml
while the `go get rsc.io/pdf` failure is fixed upstream
(rsc/pdf#4), check out manually the repository from github and put it
in the correct place under $GOPATH.
=> travis: workaround go-get-insecure for rsc.io/pdf

vg/vgtex/canvas.go, vg/vgtex/testdata/scatter_golden.tex
- fix a bug introduced by the `New`/`NewDocument` split.
- updated reference file.
this could have been caught if the generation of the PDF was performed during the test but... adding `LaTeX` as a test pre-requisite sounds less than ideal.
=> vg/vgtex: fix generation of PGF document

plotutil/add.go
This CL removes the use of maps to collect legend entries in favor of
slices so the legends are populated by insertion order.
This makes sure the order is stable.
Fixes #268.
=> plotutil: make legend entries ordered by insertion

internal/cmpimg/cmpimg.go, plotter/general_test.go, vg/vg_test.go
This CL introduces the internal package cmpimg which allows to reliably
compare whether two images are the same, taking into account
idiosyncracies of the gonum/plot-supported image formats.
Fixes #280
=> all: implement a more reliable image comparison

palette/palette.go
When a user specifies a very dense palette (see #290 for an example), floating point error can accumulate resulting in unexpected color.Color values (zero in the case above). Rather than warning users to avoid overly dense palettes, just avoid the error by using multiplication rather than successive addition.
@sbinet @jasonpfox Please take a look.
=> palette: avoid floating point errors with dense palettes

vg/font.go, vg/font_syscall.go
...so that it can be excluded in compilation environments that don't allow syscalls.
=> Moved vg syscall to separate file.

vg/vgimg/vgimg.go
draw2dimg doesn't make use of the informations provided by
draw2d.FontData fields (except for the Name field.)
At least it doesn't make use of them for the `FillString` part.
Fixes gonum/plot#208.
=> vg/vgimg: drop unneeded internal fontMap cache

vg/font.go, vg/font_syscall.go, vg/font_syscall_test.go
PR gonum/plot#335 moved the vg-syscall into a different file to support
gopherjs.
But it dropped the initialization of the FontDirs global variable.
Fix this and also move the global const 'importString' closer to its
usage, in vg/font_syscall.go.
Add a test to make sure we don't regress.
=> vg: restore FontDirs initialization

vg/draw/split_horiz_example_test.go, vg/draw/split_vertical_example_test.go
These are convenience functions that would be useful for instance in splitting up a canvas to put a plot in one part and a color bar in the other part. They are not strictly necessary but I feel like it's worthwhile to have them there because Crop can be pretty confusing to use.
=> Add draw.Split* functions

palette/moreland/luminance.go
Need to calculate normalized value over whole range.
=> Correction for Luminance.At() when range min < 0

plotter/heat.go, plotter/heat_test.go
Also use this to allow plotting of ambiguously colour-mapping values
arising from when the Z-range is zero.
Fixes #302.
@eaburns @btracey @jasonpfox Please take a look.
=> plotter: allow user control of NaN values

.travis.yml
This CL enables the fast-finish mode for travis.
See:
https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/
=> travis: enable fast-finish

axis_test.go
Commit e7f526d disabled a few tests.
But they were the only ones that needed "math".
Remove (temporarily) the import of "math".
=> plot: fix axis test build

vg/fonts/mk-fonts.go
The fedorahosted.org site has been retired (since March 2017.)
This CL now downloads fonts from the new location, pagure.org.
Fixes gonum/plot#400.
=> vg/fonts: update base URL of Liberation fonts

axis.go, axis_test.go
This PR resolves #393 
This alternate Ticker is heavily based on the default with two changes:
1. There is a different condition for setting major tick interval to a
lower order of magnitude
2. There is a different mechanism for limiting label precision.  Instead
of creating a new list that is rounded until all labels at just unique,
precision is inferred by the orders of magnitude for the largest label
and the major tick interval.  This precision is passed to the float
format function.
=> axis: Added alternate Ticker "PreciseTicks"

.travis.yml, labelling_test.go
=> travis: add go-1.10.x

go.mod
=> go.mod: fix stale gonum dep

plotter/histogram.go, plotter/histogram_test.go
=> plotter: fix histogram hang for zero-width data range

plotter/sankey.go, plotter/sankey_test.go
Previously, rendering the same diagram multiple times produced differing results.
=> plotter: Ensure Sankey can be drawn more than once

vg/vgimg/vgimg.go, vg/vgimg/vgimg_test.go
Previously, the background color was always white, with no 
straightforward way to specify a transparent backgroun.
This is an alternative to #476 .
=> vgimg: Add option to specify image background color.

plotter/plotter.go
=> plotter: add XY and XYZ struct type

axis.go
Having a function named `log` is relatively annoying when one is
debugging, especially in conjunction with `goimports`:
adding `log.Fatalf("foo")` statements is confusing `goimports` as a
function with the name `log` is already defined.
Rename `log` into `logf`.
=> plot: rename log into logf

vg/vgsvg/vgsvg.go
AFAICS this field is not used and never was.
=> vg/svg: remove unused field

vg/vgsvg/vgsvg.go
This was missed in the fix for DPI removal.
=> vg/vgsvg: update comment for NewWith

vg/vgimg/vgimg.go
This concerts from (theta,phi) that is used by vg to (theta_1,theta_2) that is used by gg.
=> vgimg: translate to gg arc end point concept

version.go
=> plot: add Version API for Go modules

.travis.yml
In 4f1973df78022b5113212a4502cdd3a7cf1c8d5c, we added bootstrap code
to fix #179 and start xvfb for the benefit of the vg/vgx11 backend.
vg/vgx11 has since been removed from gonum/plot.
So remove the xvfb startup as well.
=> ci: remove xvfb initialization

.travis.yml, appveyor.yml, go.mod
=> all: update for go1.14 release

vg/vgimg/vgimg.go
=> vg/vgimg: document that images are copied in UseImage

vg/draw/canvas.go, vg/draw/draw_test.go
=> vg/draw: add support for .tex to NewFormattedCanvas and plot.Plot.Save

plot.go
gonum/plot#587 updated vg/draw.NewFormattedCanvas to handle .tex files,
but we didn't update the documentation of plot.Plot.{Save,WriterTo}
=> plot: update Plot.WriterTo documentation

go.mod, go.sum, vg/vggio/example_vg_test.go, vg/vggio/vg.go
Use `layout.Context` instead of `system.FrameEvent` as the former is what we really use, and is "more general" than the latter.
=> vg/vggio: use layout.Context as hook into Gio

CONTRIBUTING.md
This change helps new contributors to the plot repository find the contribution guidelines that are hosted in a different repository.
=> doc: create CONTRIBUTING.md

cmpimg/cmpimg.go, go.mod, go.sum, vg/vgpdf/vgpdf.go
The existing PDF functionality was based on two now-unsupported libraries:
rsc.io/pdf and github.com/jung-kurt/gofpdf
This change drops the rsc.io/pdf dependency, and moves the jung-kurt one to
a now maintained fork: github.com/phpdave11/gofpdf
I also had to replace the custom pdf comparison function (built on rsc.io/pdf)
with an existing comparison method in gofpdf. There weren't any tests here, so
I'm not sure how to be super confident the results will be the same.
=> Changes PDF handling to use supported libraries.

axis.go, legend.go, plot.go, vg/draw/text.go, vg/draw/text_plain.go, vg/font.go, vg/font_test.go, vg/vggio/vggio.go
=> all: define vg.FontExtents.Descent as a positive value to follow x/image/font/sfnt convention

.travis.yml
This mostly fixes the travis build, but it still fails with
```
=== RUN   TestCanvas
vggio_test.go:84: could not create screenshot: vggio: could not create headless window: eglInitialize failed: 0x3001
--- FAIL: TestCanvas (0.02s)
=== RUN   TestCollectionName
--- PASS: TestCollectionName (0.00s)
=== RUN   TestLabels
vggio_test.go:244: could not create screenshot: vggio: could not create headless window: eglInitialize failed: 0x3001
--- FAIL: TestLabels (0.00s)
FAIL
FAIL	gonum.org/v1/plot/vg/vggio	0.133s
```
Any suggestions?
=> travis: set up xvfb for vggio tests

.github/workflows/golangci-lint.yml, vg/vgpdf/vgpdf.go
This CL adds a package-wide, goroutine-safe cache of fonts data that can be
re-used across vgpdf.Canvas values.
Fixes gonum/plot#694.
=> vg/vgpdf: add a per-package cache of PDF fonts

palette/reverse_example_test.go
=> palette: use strconv.Atoi instead of fmt.Sprintf

.github/workflows/ci.yml, .github/workflows/codecov.yml
The path is a multiline string, which includes comments in its value. This
means that the caching was not working at all, because it would include
the comment in the path. Here I'm moving the comments, which fixes the
caching so it works.
=> ci: make cache works by removing comments

plotutil/errorpoints.go
Fix off by one indexing bug in plotutil.MedianAndMinMax when determining the mean of the two inner-most elements in the slice.
=> Fix off by one indexing bug in plotutil.MedianAndMinMax

.ci/check-formatting.sh, .github/workflows/ci.yml, appveyor.yml, cmpimg/cmpimg.go, font/len.go, go.mod, go.sum, palette/brewer/brewer.go, plot.go, plotter/boxplot.go, plotter/heat.go, plotter/johnson.go, text/latex.go, text/plain.go, version.go, vg/draw/canvas.go, vg/len.go, vg/vggio/vggio_test.go, vg/vgpdf/vgpdf.go, vg/vgsvg/vgsvg.go
=> all: bump to Go-1.19

.github/workflows/codecov.yml
Signed-off-by: Sebastien Binet <binet@cern.ch>
=> ci: use Go-1.19 in codecov

.github/workflows/ci.yml
The behaviour of latest breaks some golden file based tests, so use the last known good version.
=> ci: explicitly use ubuntu-20.04

plotutil/main.go
=> Adds plotutil example image width/height unit

.github/workflows/ci.yml, .github/workflows/lint.yml, appveyor.yml, go.mod, go.sum
=> all: bump to Go-1.20, drop Go-1.18

vg/recorder/recorder.go
=> vg/recorder: drop unneeded field from Canvas.

.github/workflows/ci.yml, .github/workflows/codecov.yml, .github/workflows/lint.yml, go.mod
=> all: bump Go-1.22, drop Go-1.20

go.mod, go.sum
This CL bumps go-fonts/liberation@v0.5.0 to cope with an uneducated history rewrite that happened with liberation@v0.4.0.
=> all: bump go-fonts/liberation@v0.5.0, go-latex/latex@v0.1.0

go.mod, go.sum
This CL bumps go-fonts/liberation@v0.5.0 to cope with an uneducated history rewrite that happened with liberation@v0.4.0.
=> all: bump go-fonts/liberation@v0.4.1, go-latex/latex@v0.0.1

palette/moreland/luminance.go, palette/moreland/luminance_test.go, palette/moreland/smooth.go, palette/moreland/smooth_test.go
Fixes https://github.com/gonum/plot/issues/798.
This PR fixes a panic in the `Palette` method caused by a floating-point precision error, where the computed value `v` slightly exceeds the upper bound `l.max`.
As shown in the above screenshot, we have the following values:
- `l.min = 0.3402859786606234`
- `l.max = 15.322841335211892`
- `n = 15`
- `delta = 1.0701825254679478`
- `i = 14`
- `v = 15.322841335211894` (note here `v` is `0.000000000000002` greater than `l.max`)
The expected calculation of `delta`:
```
delta = (l.max - l.min) / (n - 1)
= (15.322841335211892 - 0.3402859786606234) / (15 - 1)
= 1.0701825254679478
```
This confirms that `delta` is correct and has no floating-point error.
Next, the expected calculation of `v`:
```
v = l.min + (delta  * i)
= 0.3402859786606234 + …
```
=> palette/moreland: fix floating-point arithmetic error in Palette

axis.go, plotter/image.go, plotter/johnson.go, vg/vgimg/vgimg_test.go
We can use the built-in `min` and `max` functions since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
=> all: use built-in min and max functions
